application: kaeruofvim
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /stylesheets
  static_dir: stylesheets

- url: /imgs
  static_dir: imgs

- url: /(guest|sign)
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
